name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: make install

      - name: Check formatting
        run: make format-check

      - name: Lint
        run: make lint

      - name: Type check
        run: make typecheck

      - name: Build
        run: make build

      - name: Test
        run: make test
        env:
          DISPLAY: ":99.0"

  package:
    runs-on: ubuntu-latest
    needs: format-and-lint
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: make install

      - name: Package extension
        run: make package

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: forge-cockpit.vsix
          path: "*.vsix"

      - name: Upload UI build
        uses: actions/upload-artifact@v4
        with:
          name: forge-cockpit-ui-dist
          path: forge-cockpit-ui/dist/

  auto-fix:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: format-and-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: make install

      - name: Format and fix
        run: |
          make format
          make lint-fix

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-fix: format and lint"
            git push
          fi
