name: Documentation
description: Report documentation issues
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What's wrong with the docs?
      placeholder: The documentation is unclear about...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is this documented?
      placeholder: README.md, docs/api.md, etc.
    validations:
      required: false
