name: Other
description: Questions or general discussion
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question or Issue
      description: What would you like to discuss?
      placeholder: I have a question about...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
