name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formatting-and-linting:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: make install
    
    - name: Check code formatting
      run: make format-check
    
    - name: Run ESLint
      run: make lint
    
    - name: Run TypeScript checks
      run: make typecheck
    
    - name: Build project
      run: make build